import { request } from './client';

export const campusApi = {
  // Rooms & Hostel
  getRooms: () => request<any[]>({ method: 'GET', url: '/rooms' }, []),
  createRoom: (payload: any) => request({ method: 'POST', url: '/rooms/create-room', data: payload }),
  updateRoom: (id: string, payload: any) => request({ method: 'PATCH', url: `/rooms/${id}`, data: payload }),
  deleteRoom: (id: string) => request({ method: 'DELETE', url: `/rooms/${id}` }),
  getHostels: () => request<any[]>({ method: 'GET', url: '/hostel' }, []),

  // Mess & Laundry
  getMessMenus: () => request<any[]>({ method: 'GET', url: '/mess' }, []),
  getLaundryLogs: () => request<any[]>({ method: 'GET', url: '/laundry' }, []),

  // IoT Gates & Telemetry
  getIoTDevices: () => request<any[]>({ method: 'GET', url: '/iot/devices' }, []),
  getIoTLogs: () => request<any[]>({ method: 'GET', url: '/iot/logs' }, []),
  syncIoT: (payload: any) => request({ method: 'POST', url: '/iot/sync', data: payload }),

  // Physical Security
  getGateEntries: () => request<any[]>({ method: 'GET', url: '/gate-entries' }, []),
  createGateEntry: (payload: any) => request({ method: 'POST', url: '/gate-entries/create-gate-entry', data: payload }),
  getVisitorLogs: () => request<any[]>({ method: 'GET', url: '/visitor-logs' }, []),
  createVisitorLog: (payload: any) => request({ method: 'POST', url: '/visitor-logs/create-visitor-log', data: payload }),
  getIncidents: () => request<any[]>({ method: 'GET', url: '/incidents' }, []),
  createIncident: (payload: any) => request({ method: 'POST', url: '/incidents/create-incident', data: payload }),

  // Facilities & Inventory
  getInventory: () => request<any[]>({ method: 'GET', url: '/inventory' }, []),
  getTransportRoutes: () => request<any[]>({ method: 'GET', url: '/transport' }, []),
  getMaintenanceRequests: () => request<any[]>({ method: 'GET', url: '/maintenance' }, []),
  getLibraryBooks: () => request<any[]>({ method: 'GET', url: '/books' }, []),

  // SMS Gateway & Automated Guardian Alerts
  sendSmsBroadcast: (payload: any) => request({ method: 'POST', url: '/notifications/sms/broadcast', data: payload }),
  triggerAttendanceShortageSms: (threshold = 75) => request({ method: 'POST', url: '/notifications/sms/trigger-attendance-alerts', data: { threshold } }),
  triggerFeeDueSms: () => request({ method: 'POST', url: '/notifications/sms/trigger-fee-alerts', data: {} }),
  getSmsLogs: (params?: any) => request<any[]>({ method: 'GET', url: '/notifications/sms/logs', params }, []),
  getSmsStats: () => request<any>({ method: 'GET', url: '/notifications/sms/stats' }, {
    totalSent: 1240,
    sentToday: 180,
    failed: 4,
    successRate: 99.6,
    totalCostBdt: 620.4,
    remainingWalletBalanceBdt: 42500,
  }),

  // EHS Hazardous Waste & Bunker Incompatibility Matrix
  getEhsContainers: (params?: any) => request<any[]>({ method: 'GET', url: '/ehs/containers', params }, []),
  createEhsContainer: (payload: any) => request({ method: 'POST', url: '/ehs/containers', data: payload }),
  logEhsContainer: (payload: any) => request({ method: 'POST', url: '/ehs/containers', data: payload }),
  getEhsManifests: () => request<any[]>({ method: 'GET', url: '/ehs/manifests' }, [
    {
      _id: "mnf-1",
      manifestNumber: "EPA-MNF-2026-088",
      transporterName: "EnviroSafe Transport Corp.",
      transporterEpaId: "EPA-MD-88390",
      tsdfFacility: "Apex High-Temp Incineration Facility #4",
      treatmentMethod: "HIGH_TEMP_INCINERATION",
      containers: ["EHS-DRUM-901", "EHS-DRUM-902", "EHS-DRUM-903"],
      containerCount: 3,
      dispatchedAt: "2026-10-01T10:00:00Z",
      status: "CERTIFIED_DESTRUCTION",
    },
    {
      _id: "mnf-2",
      manifestNumber: "EPA-MNF-2026-089",
      transporterName: "CleanHarbors Environmental Services",
      transporterEpaId: "EPA-MA-10492",
      tsdfFacility: "Eastern Acid Neutralization Plant #2",
      treatmentMethod: "NEUTRALIZATION_STABILIZATION",
      containers: ["EHS-DRUM-904", "EHS-DRUM-905"],
      containerCount: 2,
      dispatchedAt: "2026-10-02T14:30:00Z",
      status: "IN_TRANSIT",
    },
  ]),
  validateBunkerStorage: (payload: any) => request({ method: 'POST', url: `/ehs/containers/validate-bunker`, data: payload }, {
    compatible: true,
    message: "SAFE: Storage configuration compliant with OSHA 1910.120 reactive segregation standard.",
    reactionRisk: "MINIMAL",
  }),
  issueUniformEhsManifest: (payload: any) => request({ method: 'POST', url: '/ehs/manifests/issue', data: payload }),
  recordEhsDestruction: (payload: any) => request({ method: 'POST', url: '/ehs/manifests/record-destruction', data: payload }),
  getEhsMetrics: () => request<any>({ method: 'GET', url: '/ehs/metrics' }, null),

  // Part 5: Daily Workers & Daily Wages (DW-01 to DW-36)
  getDailyWorkers: () => request<any[]>({ method: 'GET', url: '/daily-workers/workers' }, [
    {
      _id: 'dw-01',
      workerCode: 'DW-2026-0081',
      fullName: 'Mohammad Rafiqul Islam',
      phone: '+880 1712-445588',
      skillGrade: 'SKILLED',
      trades: ['Masonry', 'Plastering'],
      engagementType: 'DIRECT',
      nationalIdHash: 'NID-7729104829',
      idDocumentVerified: true,
      ageVerifiedAdult: true,
      paymentMethod: 'WALLET',
      status: 'ACTIVE',
      totalAdvanceBalance: 1200,
      safetyInductionCompleted: true,
    },
    {
      _id: 'dw-02',
      workerCode: 'DW-2026-0082',
      fullName: 'Nurul Alam Mia',
      phone: '+880 1823-998877',
      skillGrade: 'FOREMAN',
      trades: ['Structural RCC', 'Bar Bending', 'Safety Lead'],
      engagementType: 'CONTRACTOR',
      contractorName: 'Bengal Engineering & Contractors Ltd.',
      nationalIdHash: 'NID-9928103948',
      idDocumentVerified: true,
      ageVerifiedAdult: true,
      paymentMethod: 'BANK',
      status: 'ACTIVE',
      totalAdvanceBalance: 0,
      safetyInductionCompleted: true,
    },
    {
      _id: 'dw-03',
      workerCode: 'DW-2026-0083',
      fullName: 'Sohel Rana',
      phone: '+880 1911-332211',
      skillGrade: 'HELPER',
      trades: ['General Labor', 'Material Handling'],
      engagementType: 'DIRECT',
      nationalIdHash: 'NID-3349102941',
      idDocumentVerified: true,
      ageVerifiedAdult: true,
      paymentMethod: 'CASH',
      status: 'ACTIVE',
      totalAdvanceBalance: 500,
      safetyInductionCompleted: true,
    },
  ]),
  createDailyWorker: (payload: any) => request({ method: 'POST', url: '/daily-workers/workers', data: payload }),
  getWageRateCards: () => request<any[]>({ method: 'GET', url: '/daily-workers/rate-cards' }, [
    { skillGrade: 'HELPER', title: 'General Site Helper', basis: 'DAY', rate: 650, overtimeMultiplier: 1.5, holidayMultiplier: 2.0, nightMultiplier: 1.25 },
    { skillGrade: 'SEMI_SKILLED', title: 'Assistant Mason / Carpenter', basis: 'DAY', rate: 850, overtimeMultiplier: 1.5, holidayMultiplier: 2.0, nightMultiplier: 1.25 },
    { skillGrade: 'SKILLED', title: 'Master Mason / Welder / Electrician', basis: 'DAY', rate: 1150, overtimeMultiplier: 1.5, holidayMultiplier: 2.0, nightMultiplier: 1.25 },
    { skillGrade: 'FOREMAN', title: 'Site Gang Lead & Supervisor', basis: 'DAY', rate: 1500, overtimeMultiplier: 1.5, holidayMultiplier: 2.0, nightMultiplier: 1.25 },
  ]),
  getMusterEntries: (params?: any) => request<any[]>({ method: 'GET', url: '/daily-workers/muster', params }, [
    {
      _id: 'mst-1',
      workDate: '2026-10-04',
      workerName: 'Mohammad Rafiqul Islam',
      skillGrade: 'SKILLED',
      costObjectName: 'Hostel Pro Residential Complex Phase-2 Wing C',
      dayFraction: 1.0,
      regularHours: 8.0,
      overtimeHours: 2.0,
      nightHours: 0,
      isHolidayWork: false,
      checkInMethod: 'FACE_VERIFIED',
      status: 'APPROVED',
      supervisorName: 'Engr. Mahbubur Rahman',
      ghostWorkerFlag: false,
      calculatedGross: 1437.5,
    },
    {
      _id: 'mst-2',
      workDate: '2026-10-04',
      workerName: 'Nurul Alam Mia',
      skillGrade: 'FOREMAN',
      costObjectName: 'Multi-Storied Doctors & Staff Residence Tower',
      dayFraction: 1.0,
      regularHours: 8.0,
      overtimeHours: 3.0,
      nightHours: 1.0,
      isHolidayWork: false,
      checkInMethod: 'QR',
      status: 'VERIFIED',
      supervisorName: 'Engr. Mahbubur Rahman',
      ghostWorkerFlag: false,
      calculatedGross: 2109.38,
    },
    {
      _id: 'mst-3',
      workDate: '2026-10-04',
      workerName: 'Sohel Rana',
      skillGrade: 'HELPER',
      costObjectName: 'Campus Central Drain & Road Overhaul',
      dayFraction: 0.5,
      regularHours: 4.0,
      overtimeHours: 0,
      nightHours: 0,
      isHolidayWork: false,
      checkInMethod: 'SUPERVISOR',
      status: 'SUPERVISOR_SUBMITTED',
      supervisorName: 'Site Supervisor Kabir Hossain',
      ghostWorkerFlag: false,
      calculatedGross: 325.0,
    },
  ]),
  submitMusterEntry: (payload: any) => request({ method: 'POST', url: '/daily-workers/muster', data: payload }),
  verifyMusterBatch: (payload: any) => request({ method: 'POST', url: '/daily-workers/muster/verify', data: payload }),
  calculateWagePeriod: (payload: any) => request({ method: 'POST', url: '/daily-workers/wages/calculate', data: payload }),
  disburseWageBatch: (payload: any) => request({ method: 'POST', url: '/daily-workers/wages/disburse', data: payload }),
  getDailyWorkerMetrics: () => request<any>({ method: 'GET', url: '/daily-workers/metrics' }, {
    totalActiveWorkers: 148,
    todayMusterCount: 142,
    ghostAlertsCount: 0,
    pendingWageDisbursement: 184500,
  }),
  getGhostWorkerAudit: () => request<any>({ method: 'GET', url: '/daily-workers/ghost-audit' }, {
    totalAudited: 200,
    activeFlagsCount: 0,
    integrityScore: 98,
    anomalies: [],
  }),

  // Part 6: Construction & Capital Projects (CN-01 to CN-38)
  getConstructionProjects: () => request<any[]>({ method: 'GET', url: '/construction/projects' }, [
    {
      _id: 'cn-prj-1',
      code: 'PRJ-2026-001',
      name: '10-Storied Multipurpose Academic & Auditorium Complex',
      projectType: 'NEW_BUILD',
      executionMode: 'CONTRACTOR',
      fundCode: 'FUND_40_CAPITAL',
      sponsorUnit: 'Directorate of Planning & Development',
      projectManagerName: 'Prof. Engr. Tanvir Ahmed, FIEB',
      approvedBudget: 450000000,
      contingencyPct: 5.0,
      committedCost: 385000000,
      actualCost: 218500000,
      plannedStart: '2025-01-15T00:00:00Z',
      plannedEnd: '2027-06-30T00:00:00Z',
      state: 'IN_PROGRESS',
      cipAccountCode: '1500-CIP-BUILDING',
    },
    {
      _id: 'cn-prj-2',
      code: 'PRJ-2026-002',
      name: 'High-Tech Skill Lab & Robotic Surgery Training Facility',
      projectType: 'RENOVATION',
      executionMode: 'MIXED',
      fundCode: 'FUND_40_CAPITAL',
      sponsorUnit: 'Medical Education Unit',
      projectManagerName: 'Dr. Shahriar Kabir',
      approvedBudget: 65000000,
      contingencyPct: 5.0,
      committedCost: 58000000,
      actualCost: 52000000,
      plannedStart: '2025-08-01T00:00:00Z',
      plannedEnd: '2026-11-30T00:00:00Z',
      state: 'PRACTICALLY_COMPLETE',
      cipAccountCode: '1510-CIP-LAB-FACILITY',
    },
  ]),
  createConstructionProject: (payload: any) => request({ method: 'POST', url: '/construction/projects', data: payload }),
  getConstructionProjectDetails: (id: string) => request<any>({ method: 'GET', url: `/construction/projects/${id}` }, {
    wbsNodes: [
      { code: 'WBS-1.0', name: 'Substructure & Deep Piling', budgetAmount: 85000000, actualSpent: 84200000, weightPct: 20 },
      { code: 'WBS-2.0', name: 'Superstructure RCC Framing (Floors 1-10)', budgetAmount: 180000000, actualSpent: 112000000, weightPct: 40 },
      { code: 'WBS-3.0', name: 'MEP (Electrical, HVAC, Central Medical Gas)', budgetAmount: 110000000, actualSpent: 18500000, weightPct: 25 },
      { code: 'WBS-4.0', name: 'Architectural Finishes & Acoustic Cladding', budgetAmount: 75000000, actualSpent: 3800000, weightPct: 15 },
    ],
    boqItems: [
      { itemCode: 'BOQ-RCC-M25', description: 'Ready-mix Concrete Grade M-25 Casting including shuttering', unit: 'm3', quantity: 4500, unitRate: 14500, amount: 65250000 },
      { itemCode: 'BOQ-STL-500W', description: '500W Deformed High Yield Steel Rebars Reinforcement', unit: 'MT', quantity: 620, unitRate: 115000, amount: 71300000 },
      { itemCode: 'BOQ-BRK-AUTO', description: 'First Class Auto Kiln Bricks Wall Plastering 1:4 Mortar', unit: 'sqm', quantity: 18500, unitRate: 1450, amount: 26825000 },
    ],
  }),
  getRunningBills: (params?: any) => request<any[]>({ method: 'GET', url: '/construction/running-bills', params }, [
    {
      _id: 'ra-05',
      billNumber: 5,
      contractorName: 'Bengal Engineering & Contractors Ltd.',
      periodFrom: '2026-09-01',
      periodTo: '2026-09-30',
      grossWorkDoneToDate: 218500000,
      previousCertified: 186000000,
      thisBillGross: 32500000,
      retentionDeducted: 1625000, // 5%
      advanceRecovered: 3250000, // 10%
      materialRecoveryDeducted: 1420000, // University issued cement/steel
      taxWithheld: 1625000, // 5% AIT
      netPayable: 24580000,
      status: 'APPROVED',
      certifiedBy: 'Chief Engineer K. R. Chowdhury',
      apInvoiceRef: 'INV-RA-05-891023',
    },
  ]),
  createRunningBill: (payload: any) => request({ method: 'POST', url: '/construction/running-bills', data: payload }),
  approveRunningBill: (id: string, payload: any) => request({ method: 'PATCH', url: `/construction/running-bills/${id}/approve`, data: payload }),
  submitVariationOrder: (payload: any) => request({ method: 'POST', url: '/construction/variation-orders', data: payload }),
  instructVariationOrder: (id: string, payload: any) => request({ method: 'PATCH', url: `/construction/variation-orders/${id}/instruct`, data: payload }),
  submitDailySiteReport: (payload: any) => request({ method: 'POST', url: '/construction/site-reports', data: payload }),
  capitalizeProjectToAssets: (payload: any) => request({ method: 'POST', url: '/construction/capitalize', data: payload }),
  getConstructionMetrics: () => request<any>({ method: 'GET', url: '/construction/metrics' }, {
    totalCapitalProjects: 8,
    activeInProgressCount: 5,
    totalPortfolioBudget: 840000000,
    totalActualSpent: 412500000,
    pendingRaBillsCount: 2,
    totalRetentionSecured: 20625000,
  }),
  getProjectEvmAnalysis: (id: string) => request<any>({ method: 'GET', url: `/construction/projects/${id}/evm` }, {
    projectId: id,
    projectName: '10-Storied Multipurpose Academic & Auditorium Complex',
    bac: 450000000,
    pv: 247500000,
    ev: 235800000,
    ac: 218500000,
    cpi: 1.08,
    spi: 0.95,
    eac: 416666666,
    vac: 33333334,
    physicalPct: 52.4,
    plannedPct: 55.0,
    healthStatus: 'HEALTHY',
    materialYields: [
      {
        material: '53-Grade Portland Pozzolana Cement (Bags)',
        theoreticalRequired: 38250,
        actualIssuedFromStore: 39100,
        variancePct: 2.22,
        isWithinTolerance: true,
        allowedTolerancePct: 3.0,
      },
      {
        material: '500W Deformed Steel Rebars (Metric Tons)',
        theoreticalRequired: 620.0,
        actualIssuedFromStore: 631.5,
        variancePct: 1.85,
        isWithinTolerance: true,
        allowedTolerancePct: 2.5,
      },
      {
        material: 'Sylhet Coarse Sand FM 2.5 (Cubic Feet)',
        theoreticalRequired: 145000,
        actualIssuedFromStore: 151000,
        variancePct: 4.14,
        isWithinTolerance: false,
        allowedTolerancePct: 3.5,
        auditAlert: 'Sand wastage exceeded 3.5% threshold. Site Engineer investigation flagged.',
      },
    ],
  }),
};


