import { request } from './client';

export const complianceApi = {
  // Disciplinary & Integrity
  getDisciplinaryInfractions: () => request<any[]>({ method: 'GET', url: '/disciplinary/infractions' }, [
    { _id: 'INF-2026-011', infractionNumber: 'INF-2026-011', studentId: 'STU-2026003', studentName: 'Ethan Gallagher', title: 'Examination Hall Unauthorized Material Possession', severity: 'HIGH', status: 'UNDER_REVIEW', description: 'Possession of unauthorized study notes during Anatomy semester examination.', reportedAt: '2026-09-15T11:30:00Z' },
    { _id: 'INF-2026-012', infractionNumber: 'INF-2026-012', studentId: 'STU-2026001', studentName: 'Marcus Chen', title: 'Hostel Curfew Protocol Non-Compliance', severity: 'LOW', status: 'WARNED', description: 'Late campus perimeter entry past 22:30 without warden gate pass.', reportedAt: '2026-09-18T23:15:00Z' },
    { _id: 'INF-2026-013', infractionNumber: 'INF-2026-013', studentId: 'STU-2026005', studentName: 'Liam O\'Connor', title: 'Clinical Lab Biosafety Equipment Tampering', severity: 'MEDIUM', status: 'SCHEDULED_FOR_HEARING', description: 'Disregard of containment protocols in microbiology laboratory centrifuge area.', reportedAt: '2026-09-22T14:45:00Z' },
  ]),
  reportDisciplinaryInfraction: (payload: any) => request({ method: 'POST', url: '/disciplinary/infractions', data: payload }),
  getDisciplinaryHearings: () => request<any[]>({ method: 'GET', url: '/disciplinary/hearings' }, [
    { _id: 'HRG-2026-004', caseNumber: 'CASE-INF-2026-011', hearingDate: '2026-10-05T10:00:00Z', tribunal: 'Academic Integrity Committee', venue: 'Senate Chamber', notes: 'Hearing to review physical evidence and student defense regarding exam misconduct.', status: 'SCHEDULED' },
    { _id: 'HRG-2026-005', caseNumber: 'CASE-INF-2026-013', hearingDate: '2026-10-08T14:00:00Z', tribunal: 'Biosafety Review Board', venue: 'Boardroom B', notes: 'Assessment of lab containment violation and remedial retraining sanction.', status: 'SCHEDULED' },
  ]),
  scheduleDisciplinaryHearing: (payload: any) => request({ method: 'POST', url: '/disciplinary/hearings', data: payload }),
  updateHearingOutcome: (id: string, payload: any) => request({ method: 'PATCH', url: `/disciplinary/hearings/${id}/outcome`, data: payload }),

  // Career & Placement
  getJobPostings: () => request<any[]>({ method: 'GET', url: '/placement/jobs' }, [
    { _id: 'JOB-101', title: 'Junior Clinical Resident', department: 'Cardiology', location: 'Chittagong Medical Center', salary: '৳ 45,000 - 60,000', deadline: '2026-10-15' },
    { _id: 'JOB-102', title: 'Biomedical Research Fellow', department: 'Microbiology', location: 'Apollo Genomics Lab', salary: '৳ 50,000 - 75,000', deadline: '2026-10-30' },
    { _id: 'JOB-103', title: 'Resident Medical Officer (RMO)', department: 'Emergency & Critical Care', location: 'Square Hospital Annex', salary: '৳ 65,000 - 85,000', deadline: '2026-11-10' },
  ]),
  createJobPosting: (payload: any) => request({ method: 'POST', url: '/placement/jobs', data: payload }),
  applyJobPosting: (payload: any) => request({ method: 'POST', url: '/placement/apply', data: payload }),
  getJobApplications: () => request<any[]>({ method: 'GET', url: '/placement/applications' }, []),

  // Feedback & Quality Surveys
  getFeedbackSurveys: () => request<any[]>({ method: 'GET', url: '/feedback/surveys' }, []),
  createFeedbackSurvey: (payload: any) => request({ method: 'POST', url: '/feedback/surveys', data: payload }),
  submitFeedbackResponse: (payload: any) => request({ method: 'POST', url: '/feedback/responses', data: payload }),

  // Statutory Accreditation
  getAccreditationReports: () => request<any[]>({ method: 'GET', url: '/accreditation-report' }, []),
  generateAccreditationReport: (payload: any) => request({ method: 'POST', url: '/accreditation-report/generate', data: payload }),

  // Governance & System
  getGrievances: () => request<any[]>({ method: 'GET', url: '/grievances' }, []),
  submitGrievance: (payload: any) => request({ method: 'POST', url: '/grievances/submit', data: payload }),
  getNotices: () => request<any[]>({ method: 'GET', url: '/notices' }, []),
  getAuditLogs: (params?: Record<string, any>) => request<any>({ method: 'GET', url: '/audit-logs', params }, { logs: [], meta: { page: 1, limit: 10, total: 0 } }),
  globalSearch: (query: string) => request({ method: 'GET', url: `/search?q=${encodeURIComponent(query.trim())}` }),

  // Universal Campus Requisitions (Stock, Assets, Funds)
  getRequisitions: (params?: any) => request<any[]>({ method: 'GET', url: '/requisitions', params }, [
    {
      _id: "REQ-2026-001",
      reqNumber: "REQ-2026-001",
      title: "Gray's Anatomy 42nd Edition & Robbins Pathology Sets",
      requestorName: "Prof. Clara Oswald",
      department: "Library & Information Science",
      category: "LIBRARY",
      itemType: "ASSET",
      quantity: 25,
      estimatedCost: 185000,
      urgency: "NORMAL",
      status: "APPROVED_BY_BOARD",
      justification: "Semester enrollment surge in 1st year MBBS requires textbook reserve expansion.",
      submittedAt: "2026-09-18T10:30:00Z",
    },
    {
      _id: "REQ-2026-002",
      reqNumber: "REQ-2026-002",
      title: "Centrifuge Tubes, Culture Media & Gram Stain Reagents",
      requestorName: "Dr. James Sterling",
      department: "Microbiology & Pathology Lab",
      category: "LABORATORY",
      itemType: "CONSUMABLE",
      quantity: 500,
      estimatedCost: 95000,
      urgency: "URGENT",
      status: "PENDING_HOD",
      justification: "Routine batch diagnostic testing materials for 2nd Professional exam practicums.",
      submittedAt: "2026-09-22T14:15:00Z",
    },
    {
      _id: "REQ-2026-003",
      reqNumber: "REQ-2026-003",
      title: "Interactive Smart Laser Projectors & Audio Clickers",
      requestorName: "Dr. Sarah Jenkins",
      department: "Academic Affairs (Classroom Facilities)",
      category: "FACULTY_CLASSROOM",
      itemType: "ASSET",
      quantity: 4,
      estimatedCost: 320000,
      urgency: "NORMAL",
      status: "APPROVED_HOD",
      justification: "Replacement of burnt lamp projectors in Lecture Halls 101 and 104.",
      submittedAt: "2026-09-25T09:00:00Z",
    },
    {
      _id: "REQ-2026-004",
      reqNumber: "REQ-2026-004",
      title: "Dormitory High-Density Foam Mattresses & Water Purifier Filters",
      requestorName: "Robert Williams",
      department: "Hostel & Estate Management",
      category: "HOSTEL_LOGISTICS",
      itemType: "ASSET",
      quantity: 60,
      estimatedCost: 450000,
      urgency: "CRITICAL",
      status: "DISPATCHED_TO_PO",
      justification: "Equipping incoming freshman residential wing Block C before term commencement.",
      submittedAt: "2026-09-27T11:45:00Z",
    },
  ]),
  createRequisition: (payload: any) => request({ method: 'POST', url: '/requisitions', data: payload }),
  updateRequisitionStatus: (id: string, payload: any) => request({ method: 'PATCH', url: `/requisitions/${id}/status`, data: payload }),

  // Capital Campus Development & Daily Ledger Tracking
  getDevelopmentProjects: () => request<any[]>({ method: 'GET', url: '/development/projects' }, [
    {
      _id: "DEV-PRJ-01",
      code: "PRJ-MED-2026-A",
      title: "Advanced Anatomy VR Simulation Suite & Skill Lab Expansion",
      category: "ACADEMIC_INFRASTRUCTURE",
      projectDirector: "Prof. Sarah Connor",
      allocatedBudget: 25000000,
      totalDisbursed: 14200000,
      committedDues: 3800000,
      remainingBuffer: 7000000,
      startDate: "2026-01-10",
      targetCompletion: "2026-12-31",
      status: "IN_PROGRESS",
      progressPct: 62,
    },
    {
      _id: "DEV-PRJ-02",
      code: "PRJ-NET-2026-B",
      title: "Campus-Wide Gigabit Fiber Optic Backbone & WiFi 6 Gateway",
      category: "ICT_TELECOM",
      projectDirector: "Engr. Tariqul Islam",
      allocatedBudget: 12000000,
      totalDisbursed: 9800000,
      committedDues: 1100000,
      remainingBuffer: 1100000,
      startDate: "2026-03-01",
      targetCompletion: "2026-10-31",
      status: "IN_PROGRESS",
      progressPct: 85,
    },
    {
      _id: "DEV-PRJ-03",
      code: "PRJ-HST-2026-C",
      title: "Hostel North Wing Central Dining Hall & Solar Array",
      category: "RESIDENTIAL_ESTATE",
      projectDirector: "Ar. Mahmudul Hasan",
      allocatedBudget: 18500000,
      totalDisbursed: 6400000,
      committedDues: 4100000,
      remainingBuffer: 8000000,
      startDate: "2026-05-15",
      targetCompletion: "2027-04-30",
      status: "IN_PROGRESS",
      progressPct: 38,
    },
  ]),
  getProjectJournals: (projectId?: string) => request<any[]>({ method: 'GET', url: projectId ? `/development/projects/${projectId}/journals` : '/development/journals' }, [
    {
      _id: "JRN-DEV-101",
      voucherNumber: "VCH-2026-09-001",
      projectId: "DEV-PRJ-01",
      projectTitle: "Advanced Anatomy VR Simulation Suite",
      date: "2026-09-15",
      title: "Reinforced Concrete Foundation & Anti-Static Flooring Installation",
      category: "CIVIL_WORKS",
      contractor: "National Engineering & Infra Consortium",
      amountPaid: 850000,
      dueAmount: 150000,
      paymentMethod: "BANK_WIRE_TRANSFER",
      bankAccount: "Sonali Bank Escrow A/C #020001889",
      invoiceRef: "INV-NEC-8891",
      status: "POSTED_TO_GAAP_LEDGER",
    },
    {
      _id: "JRN-DEV-102",
      voucherNumber: "VCH-2026-09-002",
      projectId: "DEV-PRJ-01",
      projectTitle: "Advanced Anatomy VR Simulation Suite",
      date: "2026-09-20",
      title: "Import Custom Clearance & Freight for 12 VR Haptic Headsets",
      category: "EQUIPMENT_IMPORT",
      contractor: "Biomedical Precision Devices Inc.",
      amountPaid: 1400000,
      dueAmount: 0,
      paymentMethod: "LETTER_OF_CREDIT",
      bankAccount: "City Bank LC #LC-2026-901",
      invoiceRef: "INV-BPD-4019",
      status: "POSTED_TO_GAAP_LEDGER",
    },
    {
      _id: "JRN-DEV-103",
      voucherNumber: "VCH-2026-09-003",
      projectId: "DEV-PRJ-02",
      projectTitle: "Campus-Wide Gigabit Fiber Optic Backbone",
      date: "2026-09-24",
      title: "Underground Trenching & Fiber Splice Boxes (Hostel to Hospital Link)",
      category: "TELECOM_CABLE",
      contractor: "FiberTech Bangladesh Ltd.",
      amountPaid: 450000,
      dueAmount: 200000,
      paymentMethod: "DIRECT_CHEQUE",
      bankAccount: "Sonali Bank Escrow A/C #020001889",
      invoiceRef: "INV-FT-202",
      status: "POSTED_TO_GAAP_LEDGER",
    },
    {
      _id: "JRN-DEV-104",
      voucherNumber: "VCH-2026-09-004",
      projectId: "DEV-PRJ-03",
      projectTitle: "Hostel North Wing Central Dining Hall",
      date: "2026-09-28",
      title: "Heavy Structural Steel Truss Fabrication & Anti-Rust Coating",
      category: "STRUCTURAL_STEEL",
      contractor: "Bengal Steel & Modular Builders",
      amountPaid: 620000,
      dueAmount: 380000,
      paymentMethod: "BANK_WIRE_TRANSFER",
      bankAccount: "Sonali Bank Escrow A/C #020001889",
      invoiceRef: "INV-BS-771",
      status: "PENDING_AUDIT_VERIFICATION",
    },
  ]),
  createProjectJournal: (payload: any) => request({ method: 'POST', url: '/development/journals', data: payload }),
  getDevelopmentMetrics: () => request<any>({ method: 'GET', url: '/development/metrics' }, {
    totalInvestedBudget: 55500000,
    totalDisbursedSpend: 30400000,
    totalCommittedDues: 9000000,
    totalRemainingBuffer: 16100000,
    activeProjectsCount: 3,
    weeklyBurnRate: 1920000,
    fiscalYear: "2026-2027",
  }),

  // Statutory Procurement Tendering (3-Bid Comparative Statement)
  getRequisitionBids: (reqId: string) => request<any[]>({ method: 'GET', url: `/requisitions/${reqId}/bids` }, [
    {
      bidId: "BID-101",
      vendorName: "MediTech Importers Ltd.",
      quotedAmount: 182000,
      deliveryLeadDays: 14,
      complianceScore: 96,
      status: "LOWEST_EVALUATED_BIDDER",
      warrantyMonths: 24,
    },
    {
      bidId: "BID-102",
      vendorName: "Scientific Instruments BD Co.",
      quotedAmount: 195000,
      deliveryLeadDays: 21,
      complianceScore: 92,
      status: "COMPLIANT",
      warrantyMonths: 12,
    },
    {
      bidId: "BID-103",
      vendorName: "Apex BioSciences Logistics",
      quotedAmount: 210000,
      deliveryLeadDays: 10,
      complianceScore: 88,
      status: "NON_RESPONSIVE_HIGH",
      warrantyMonths: 12,
    },
  ]),
  submitVendorBid: (payload: any) => request({ method: 'POST', url: '/requisitions/bids', data: payload }),

  // 10% Contractor Retention Money & GAAP Escrow Accounting
  getContractorRetentionEscrow: () => request<any[]>({ method: 'GET', url: '/development/retention-escrow' }, [
    {
      id: "RET-2026-01",
      projectId: "DEV-PRJ-01",
      projectTitle: "Advanced Anatomy VR Simulation Suite",
      contractor: "National Engineering Consortium",
      grossCertifiedBilled: 14200000,
      liquidDisbursed: 12780000,
      retentionMoney10Pct: 1420000,
      escrowBankAccount: "Sonali Bank Contractor Escrow #020009941",
      releaseMaturityDate: "2027-09-30",
      status: "HELD_IN_ESCROW",
    },
    {
      id: "RET-2026-02",
      projectId: "DEV-PRJ-02",
      projectTitle: "Campus Fiber Optic Backbone",
      contractor: "FiberTech Bangladesh Ltd.",
      grossCertifiedBilled: 9800000,
      liquidDisbursed: 8820000,
      retentionMoney10Pct: 980000,
      escrowBankAccount: "City Bank Escrow #110029384",
      releaseMaturityDate: "2027-05-15",
      status: "HELD_IN_ESCROW",
    },
  ]),
};
